# Generated by Django 5.2 on 2026-03-01 06:13
# 数据库初始化迁移文件，定义所有核心数据表结构

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    房屋代管系统初始迁移
    创建用户、房屋、寄养请求、任务、评价、风控等核心表
    """

    initial = True

    # 本迁移不依赖其他迁移文件
    dependencies = []

    operations = [
        # ======================== 用户相关表 ========================
        migrations.CreateModel(
            name="User",
            fields=[
                # 自增主键，用户唯一标识
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                # 登录用户名，全局唯一，索引自动创建
                ("username", models.CharField(max_length=50, unique=True)),
                # 密码哈希值，长度255足够容纳各类哈希算法结果
                ("password", models.CharField(max_length=255)),
                # 角色：host（房主）或 sitter（看护人）
                ("role", models.CharField(max_length=6)),
                # 账号创建时间
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                # 与 User.user_id 一对一关联，作为主键
                ("user_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("real_name", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=6, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                # 身份证号，用于实名认证，允许为空
                ("id_number", models.CharField(blank=True, max_length=50, null=True)),
                # 经验等级，数值越高表示经验越丰富
                ("experience_level", models.IntegerField(blank=True, null=True)),
                # 个人简介
                ("bio", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserCredit",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                # 信用分变动值，正为增加，负为扣减
                ("score_change", models.IntegerField()),
                # 变动原因说明
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "user_credit",
            },
        ),

        # ======================== 房屋相关表 ========================
        migrations.CreateModel(
            name="House",
            fields=[
                ("house_id", models.BigAutoField(primary_key=True, serialize=False)),
                # 房主用户ID，关联 User 表
                ("owner_id", models.BigIntegerField()),
                # 房屋详细地址
                ("address", models.CharField(max_length=255)),
                # 房屋描述
                ("description", models.TextField(blank=True, null=True)),
                # 是否有宠物：0-无，1-有
                ("has_pet", models.IntegerField()),
                # 可入住起始日期
                ("available_from", models.DateField()),
                # 可入住截止日期
                ("available_to", models.DateField()),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "house",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("pet_id", models.BigAutoField(primary_key=True, serialize=False)),
                # 所属房屋ID
                ("house_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=50)),
                # 宠物类型：猫、狗等
                ("type", models.CharField(max_length=50)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pet",
            },
        ),
        migrations.CreateModel(
            name="HouseTask",
            fields=[
                ("task_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                # 任务类型：喂养、遛狗、清洁等
                ("task_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                # 执行频率：daily/weekly/monthly
                ("frequency", models.CharField(max_length=6)),
            ],
            options={
                "db_table": "house_task",
            },
        ),

        # ======================== 寄养请求与流程表 ========================
        migrations.CreateModel(
            name="StayRequest",
            fields=[
                ("request_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                # 申请看护人用户ID
                ("sitter_id", models.BigIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                # 状态：pending/accepted/rejected/cancelled/completed
                ("status", models.CharField(max_length=30)),
                # 申请理由或拒绝原因
                ("reason", models.TextField(blank=True, null=True)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "stay_request",
            },
        ),
        migrations.CreateModel(
            name="StayMatchScore",
            fields=[
                ("score_id", models.BigAutoField(primary_key=True, serialize=False)),
                # 关联的寄养请求ID
                ("request_id", models.BigIntegerField()),
                # 匹配总分
                ("total_score", models.DecimalField(decimal_places=2, max_digits=5)),
                # 经验匹配分
                (
                    "experience_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                # 信用匹配分
                (
                    "credit_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                # 时间匹配分
                (
                    "time_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "stay_match_score",
            },
        ),
        migrations.CreateModel(
            name="StayStatus",
            fields=[
                ("status_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_id", models.BigIntegerField()),
                # 当前流程状态
                ("current_status", models.CharField(max_length=30)),
                # 是否需要打卡签到：0-不需要，1-需要
                ("checkin_required", models.IntegerField()),
                # 最近一次打卡时间
                ("last_checkin_time", models.DateTimeField(blank=True, null=True)),
                # 异常标记：0-正常，1-异常
                ("aborrmal_flag", models.IntegerField()),
                ("update_time", models.DateTimeField()),
            ],
            options={
                "db_table": "stay_status",
            },
        ),
        migrations.CreateModel(
            name="StayCheckinLog",
            fields=[
                ("check_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_id", models.BigIntegerField()),
                ("checkin_time", models.DateTimeField()),
                # 签到地理位置信息
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "stay_checkin_log",
            },
        ),
        migrations.CreateModel(
            name="StayTaskProgress",
            fields=[
                ("progress_id", models.BigAutoField(primary_key=True, serialize=False)),
                # 关联房屋任务ID
                ("task_id", models.BigIntegerField()),
                ("request_id", models.BigIntegerField()),
                # 完成状态：done/todo
                ("status", models.CharField(max_length=5)),
                ("update_time", models.DateTimeField()),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "stay_task_progress",
            },
        ),
        migrations.CreateModel(
            name="StayAgreement",
            fields=[
                (
                    "agreement_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("request_id", models.BigIntegerField()),
                # 房主签署状态：0-未签，1-已签
                ("signed_by_host", models.IntegerField()),
                # 看护人签署状态：0-未签，1-已签
                ("signed_by_sitter", models.IntegerField()),
                # 合同PDF文件存储路径
                ("pdf_path", models.CharField(max_length=255)),
                # 签署完成时间
                ("sign_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "stay_agreement",
            },
        ),

        # ======================== 评价与风控表 ========================
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("rating_id", models.BigAutoField(primary_key=True, serialize=False)),
                # 关联的寄养请求ID
                ("request_id", models.BigIntegerField()),
                # 评价人用户ID
                ("rater_id", models.BigIntegerField()),
                # 被评价人用户ID
                ("target_id", models.BigIntegerField()),
                # 评分，1-5分
                ("score", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "rating",
            },
        ),
        migrations.CreateModel(
            name="RiskAlert",
            fields=[
                ("alert_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                # 可能关联的具体请求ID，非必须
                ("request_id", models.BigIntegerField(blank=True, null=True)),
                # 告警类型：late_checkin/abnormal_duration/credit_drop 等
                ("alert_type", models.CharField(max_length=50)),
                # 风险等级：low/medium/high/critical
                ("level", models.CharField(max_length=6)),
                # 告警消息内容
                ("message", models.CharField(max_length=255)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "risk_alert",
            },
        ),

        # ======================== 物联网与统计表 ========================
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("data_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                # 传感器类型：temperature/humidity/door 等
                ("sensor_type", models.CharField(max_length=50)),
                # 传感器数值，字符串形式兼容多种数据格式
                ("value", models.CharField(max_length=100)),
                ("record_time", models.DateTimeField()),
            ],
            options={
                "db_table": "sensor_data",
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                ("stat_id", models.BigAutoField(primary_key=True, serialize=False)),
                # 统计类型：user_activity/house_occupancy 等
                ("stat_type", models.CharField(max_length=30)),
                # 统计对象ID，可为空（如全局统计）
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                # 指标名称：request_count/avg_score 等
                ("metric", models.CharField(max_length=50)),
                # 指标数值，保留两位小数
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=10)),
                # 统计日期
                ("stat_date", models.DateField()),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "statistics",
            },
        ),

        # ======================== 系统日志表 ========================
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=20, null=True)),
                # 操作类型：login/logout/create_request 等
                ("action", models.CharField(max_length=100)),
                # 操作目标类型：House/StayRequest 等
                ("target_type", models.CharField(blank=True, max_length=50, null=True)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=50, null=True)),
                # 日志级别：INFO/WARNING/ERROR/DEBUG
                ("log_level", models.CharField(max_length=7)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "system_log",
            },
        ),
    ]