# Generated by Django 5.2 on 2026-03-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                ("house_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("owner_id", models.BigIntegerField()),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("has_pet", models.IntegerField()),
                ("available_from", models.DateField()),
                ("available_to", models.DateField()),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "house",
            },
        ),
        migrations.CreateModel(
            name="HouseTask",
            fields=[
                ("task_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                ("task_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("frequency", models.CharField(max_length=6)),
            ],
            options={
                "db_table": "house_task",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("pet_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pet",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("rating_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_id", models.BigIntegerField()),
                ("rater_id", models.BigIntegerField()),
                ("target_id", models.BigIntegerField()),
                ("score", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "rating",
            },
        ),
        migrations.CreateModel(
            name="RiskAlert",
            fields=[
                ("alert_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                ("request_id", models.BigIntegerField(blank=True, null=True)),
                ("alert_type", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=6)),
                ("message", models.CharField(max_length=255)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "risk_alert",
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("data_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                ("sensor_type", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
                ("record_time", models.DateTimeField()),
            ],
            options={
                "db_table": "sensor_data",
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                ("stat_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("stat_type", models.CharField(max_length=30)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("metric", models.CharField(max_length=50)),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stat_date", models.DateField()),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "statistics",
            },
        ),
        migrations.CreateModel(
            name="StayAgreement",
            fields=[
                (
                    "agreement_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("request_id", models.BigIntegerField()),
                ("signed_by_host", models.IntegerField()),
                ("signed_by_sitter", models.IntegerField()),
                ("pdf_path", models.CharField(max_length=255)),
                ("sign_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "stay_agreement",
            },
        ),
        migrations.CreateModel(
            name="StayCheckinLog",
            fields=[
                ("check_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_id", models.BigIntegerField()),
                ("checkin_time", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "stay_checkin_log",
            },
        ),
        migrations.CreateModel(
            name="StayMatchScore",
            fields=[
                ("score_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_id", models.BigIntegerField()),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "experience_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "credit_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "time_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "stay_match_score",
            },
        ),
        migrations.CreateModel(
            name="StayRequest",
            fields=[
                ("request_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("house_id", models.BigIntegerField()),
                ("sitter_id", models.BigIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(max_length=30)),
                ("reason", models.TextField(blank=True, null=True)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "stay_request",
            },
        ),
        migrations.CreateModel(
            name="StayStatus",
            fields=[
                ("status_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_id", models.BigIntegerField()),
                ("current_status", models.CharField(max_length=30)),
                ("checkin_required", models.IntegerField()),
                ("last_checkin_time", models.DateTimeField(blank=True, null=True)),
                ("aborrmal_flag", models.IntegerField()),
                ("update_time", models.DateTimeField()),
            ],
            options={
                "db_table": "stay_status",
            },
        ),
        migrations.CreateModel(
            name="StayTaskProgress",
            fields=[
                ("progress_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_id", models.BigIntegerField()),
                ("request_id", models.BigIntegerField()),
                ("status", models.CharField(max_length=5)),
                ("update_time", models.DateTimeField()),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "stay_task_progress",
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=20, null=True)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(blank=True, max_length=50, null=True)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=50, null=True)),
                ("log_level", models.CharField(max_length=7)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "system_log",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=6)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserCredit",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("score_change", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("create_time", models.DateTimeField()),
            ],
            options={
                "db_table": "user_credit",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("user_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("real_name", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=6, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("id_number", models.CharField(blank=True, max_length=50, null=True)),
                ("experience_level", models.IntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
    ]
