# Generated by Django 5.2 on 2026-04-06 15:16
# 用户角色字段长度调整迁移文件

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    调整 User 表的 role 字段长度
    原设计 role 为最大6字符（host/sitter），后续业务扩展需要支持更细粒度的角色标识，
    因此将字段最大长度从6扩展至20，同时保持已有数据完全兼容。
    """

    # 依赖第一个迁移文件（初始化表结构）
    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=20),
        ),
    ]