# Generated by Django 5.2 on 2026-04-06 15:16
# 寄养协议表新增状态和签署时间字段

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    扩展 StayAgreement 模型
    新增协议状态字段和双方签署时间记录，用于细化协议签署流程
    """

    dependencies = [
        ("houses", "0002_alter_user_role"),
    ]

    operations = [
        # 新增协议状态字段，默认为 pending
        migrations.AddField(
            model_name="stayagreement",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        # 新增看护人签署时间字段，签署前为空
        migrations.AddField(
            model_name="stayagreement",
            name="sitter_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        # 新增房主签署时间字段，签署前为空
        migrations.AddField(
            model_name="stayagreement",
            name="owner_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]