# Generated by Django 5.2.6 on 2026-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_stayagreement_status_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house",
            options={"verbose_name": "房源", "verbose_name_plural": "房源"},
        ),
        migrations.AlterModelOptions(
            name="housetask",
            options={"verbose_name": "房源任务", "verbose_name_plural": "房源任务"},
        ),
        migrations.AlterModelOptions(
            name="pet",
            options={"verbose_name": "宠物", "verbose_name_plural": "宠物"},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "评价", "verbose_name_plural": "评价"},
        ),
        migrations.AlterModelOptions(
            name="riskalert",
            options={"verbose_name": "风险告警", "verbose_name_plural": "风险告警"},
        ),
        migrations.AlterModelOptions(
            name="sensordata",
            options={"verbose_name": "传感器数据", "verbose_name_plural": "传感器数据"},
        ),
        migrations.AlterModelOptions(
            name="statistics",
            options={"verbose_name": "统计记录", "verbose_name_plural": "统计记录"},
        ),
        migrations.AlterModelOptions(
            name="stayagreement",
            options={"verbose_name": "托管协议", "verbose_name_plural": "托管协议"},
        ),
        migrations.AlterModelOptions(
            name="staycheckinlog",
            options={"verbose_name": "签到记录", "verbose_name_plural": "签到记录"},
        ),
        migrations.AlterModelOptions(
            name="staymatchscore",
            options={"verbose_name": "匹配得分", "verbose_name_plural": "匹配得分"},
        ),
        migrations.AlterModelOptions(
            name="stayrequest",
            options={"verbose_name": "托管申请", "verbose_name_plural": "托管申请"},
        ),
        migrations.AlterModelOptions(
            name="staystatus",
            options={"verbose_name": "托管状态", "verbose_name_plural": "托管状态"},
        ),
        migrations.AlterModelOptions(
            name="staytaskprogress",
            options={"verbose_name": "任务进度", "verbose_name_plural": "任务进度"},
        ),
        migrations.AlterModelOptions(
            name="systemlog",
            options={"verbose_name": "系统日志", "verbose_name_plural": "系统日志"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AlterModelOptions(
            name="usercredit",
            options={"verbose_name": "信誉流水", "verbose_name_plural": "信誉流水"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "用户资料", "verbose_name_plural": "用户资料"},
        ),
        migrations.AlterField(
            model_name="stayagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待签署"),
                    ("sitter_signed", "看护人已签署"),
                    ("owner_signed", "房主已确认"),
                    ("active", "履约中"),
                    ("completed", "已完成"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
