# Generated by Django 5.2.6 on 2026-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_alter_house_options_alter_housetask_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskalert",
            name="create_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="riskalert",
            name="house_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="riskalert",
            name="level",
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="riskalert",
            name="request_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="house",
            index=models.Index(
                fields=["owner_id", "create_time"], name="house_owner_ct_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="housetask",
            index=models.Index(fields=["house_id"], name="house_task_house_idx"),
        ),
        migrations.AddIndex(
            model_name="riskalert",
            index=models.Index(
                fields=["house_id", "create_time"], name="risk_alert_house_ct_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskalert",
            index=models.Index(
                fields=["request_id", "create_time"], name="risk_alert_req_ct_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskalert",
            index=models.Index(
                fields=["level", "create_time"], name="risk_alert_level_ct_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stayrequest",
            index=models.Index(
                fields=["house_id", "status"], name="stay_req_house_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stayrequest",
            index=models.Index(
                fields=["sitter_id", "status"], name="stay_req_sitter_st_idx"
            ),
        ),
    ]
