# Generated by Django 5.2.6 on 2026-04-12 13:36
# 为高频查询字段添加数据库索引，优化查询性能

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    性能优化迁移：为核心业务表添加索引
    主要针对风险告警、托管请求等高频查询场景，通过索引加速数据检索
    """

    dependencies = [
        # 依赖前一个迁移（设置模型中文名称和协议状态枚举）
        ("houses", "0004_alter_house_options_alter_housetask_options_and_more"),
    ]

    operations = [
        # ========== 风险告警表字段索引优化 ==========
        # 告警创建时间通常作为排序和范围查询条件，建立索引可大幅提升查询效率
        migrations.AlterField(
            model_name="riskalert",
            name="create_time",
            field=models.DateTimeField(db_index=True),
        ),
        # 按房源查询告警是常见操作，为 house_id 建立单列索引
        migrations.AlterField(
            model_name="riskalert",
            name="house_id",
            field=models.BigIntegerField(db_index=True),
        ),
        # 风险等级常用于过滤条件，建立索引加速按等级筛选
        migrations.AlterField(
            model_name="riskalert",
            name="level",
            field=models.CharField(db_index=True, max_length=16),
        ),
        # 按关联的托管请求查询告警，也需要索引支持
        migrations.AlterField(
            model_name="riskalert",
            name="request_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),

        # ========== 复合索引（多字段联合索引） ==========
        # 房源表：按房主查询并排序创建时间，常见于“我的房源”列表
        migrations.AddIndex(
            model_name="house",
            index=models.Index(
                fields=["owner_id", "create_time"], name="house_owner_ct_idx"
            ),
        ),
        # 房源任务表：按房源查询任务清单
        migrations.AddIndex(
            model_name="housetask",
            index=models.Index(fields=["house_id"], name="house_task_house_idx"),
        ),
        # 风险告警：按房源 + 创建时间联合索引，用于“某房源近期告警”
        migrations.AddIndex(
            model_name="riskalert",
            index=models.Index(
                fields=["house_id", "create_time"], name="risk_alert_house_ct_idx"
            ),
        ),
        # 风险告警：按请求 + 创建时间联合索引
        migrations.AddIndex(
            model_name="riskalert",
            index=models.Index(
                fields=["request_id", "create_time"], name="risk_alert_req_ct_idx"
            ),
        ),
        # 风险告警：按等级 + 创建时间联合索引，用于“所有高危告警按时间排序”
        migrations.AddIndex(
            model_name="riskalert",
            index=models.Index(
                fields=["level", "create_time"], name="risk_alert_level_ct_idx"
            ),
        ),
        # 托管请求：按房源 + 状态联合索引，常见于“某房源的所有待处理申请”
        migrations.AddIndex(
            model_name="stayrequest",
            index=models.Index(
                fields=["house_id", "status"], name="stay_req_house_st_idx"
            ),
        ),
        # 托管请求：按看护人 + 状态联合索引，用于“某看护人的进行中订单”
        migrations.AddIndex(
            model_name="stayrequest",
            index=models.Index(
                fields=["sitter_id", "status"], name="stay_req_sitter_st_idx"
            ),
        ),
    ]