"""领域常量定义（风险等级、分页默认值）。"""

# 风险等级（在数据库中以小写形式存储）
RISK_LEVEL_LOW = "low"
RISK_LEVEL_MEDIUM = "medium"
RISK_LEVEL_HIGH = "high"
RISK_LEVEL_CRITICAL = "critical"

RISK_LEVEL_ORDER = (
    RISK_LEVEL_LOW,
    RISK_LEVEL_MEDIUM,
    RISK_LEVEL_HIGH,
    RISK_LEVEL_CRITICAL,
)

DEFAULT_PAGE_SIZE = 12
RISK_ALERTS_PAGE_SIZE = 25
